################################################################################
# Beginn des Lösungsskripts
################################################################################


#---------------------------------------------------
# Exercise  1 
#---------------------------------------------------

library(FEMS)

# a) Bank account
# Time series of transactions:
(cashflows <- timeSeries(
  rep(-8000,5), units="CHF",
  timeSequence(from="2014-02-01", by="year", length.out=5)))

# Construction of the bank account
(my.account <- bankAccount("2013-12-31", balance=200000,
  ext_transactions = cashflows, ir=0.03))

# Extraction of the cashflows
cashFlows(my.account, from="2013-01-01", to="2019-01-01")

# Extraction of the event series.
# Notice that the event series contains more information than the cashflows.
# In this case, 
evs <- events(my.account, "2013-01-01", end_date="2018-12-31")
print(evs,indices=c(-4))
# Plotting the events
plot(my.account, "2013-12-31")

# b) Reveneus from sales:
# We need the last day of a quarter.
# Try the following:
(times <- timeSequence(from="2021-03-31", by="3 months", length.out=20)) 
# Unfortunately this does not work.
# Therefore, start with the first of a quarter and substract 1 day in seconds.
# It's a workaround to always get the last day of a quarter
(times <- timeSequence(from="2021-04-01", by="3 months", length.out=20)-24*3600) 

(price <- c(rep(70, 8), 70*(1- 0.0425)^(1:12)))

idx <- Index(label = "PriceIndex", data = price, charvec = times)
plot(idx)

(volume <- timeSeries(12500 * 1.0466^(0:19), times))

# function for revenue
revenue.sales <- function(idx, vol, times) { 
  res <- idx$Data[as.character(times),] * vol[as.character(times),]
  colnames(res) = "CHF"
  res
}

# testing the function
revenue.sales(idx=idx, times=times, vol=volume)

# Constructing the object
OpCFs <- OperationalCF(
  ContractID="Sales", Currency="CHF",
  pattern = revenue.sales, # the function
  args = list( # the argument of the function
    idx = idx,  
    vol = volume,
    times = as.character(times)
  )
)

# cash flows generated by object:
cashFlows(OpCFs, "2020-12-31", "2025-12-31")

# events
evs <- events(OpCFs, "2020-12-31")
print(evs,indices=c(-4,-8,-9))

plot(OpCFs, "2020-12-31")

# c) Investment
# function generating the write-offs
(times <- timeSequence("2015-01-01", by="year", length.out=6))
write.off <- function(times) {
  timeSeries(1500000 * 0.7^(0:5), times) 
}

write.off(times)

invest <- Investments(
  ContractID = "Invest01", Currency = "CHF", 
  pattern = write.off, 
  args = list(times = times))

cashFlows(invest, "2014-12-31", "2020-01-01")

evs <- events(invest, "2014-12-31")
print(evs, indices=c(-4,-8,-9))  # pretty print funktioniert nicht.

plot(invest, "2014-12-31")

# d) Bond
b1 <- bond(start = "2020-01-01", maturity = "5 years", nominal = 10000, 
           couponFreq="3 month", coupon = 0.045)
cashFlows(b1, "2020-01-01")
plot(b1, "2020-01-01")
evs <- events(b1, "2020-01-01")
print(evs, indices=c(-4,-9))

# e) Annuity
a1 <- annuity(start = "2020-01-01", maturity = "22 years", nominal = 300000, 
           annuityFreq="1 month", ir = 0.04)
cashFlows(a1)  
plot(a1, "2020-01-01")
evs <- events(a1, "2020-01-01")
print(evs, indices=c(-4,-9), digits=2)

# f) Loan with constant amortization
mortgage <- loan("2017-01-01", nominal = 800000, ir = 0.035, maturity = "10 years",
                 irFreq="3 months", amortFreq="1 year", amort=30000)
cashFlows(mortgage)  
plot(mortgage, "2017-01-01")
evs <- events(mortgage, "2017-01-01")
print(evs, indices=c(-4,-9))


